config/routes.rb
Rails.application.routes.draw do
  root 'numbers#index'

  get '/numbers' => 'numbers#index'
  post '/numbers' => 'numbers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_action :setup

  def index
    @numbers = (@offset + 1..@offset + @quantity).to_a
  end

  private

  def setup
    @page = (params[:page] || 0).to_i
    @quantity = (params[:quantity] || 1000).to_i
    if 1000000 % @quantity == 0
      @last_page = 1000000/@quantity - 1
    else
      @last_page = 1000000/@quantity
    end
    #@page = @last_page if @page > @last_page
    @quantity = 9999 if @quantity > 9999
    @offset = @page * @quantity
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/numbers_helper.rb
module NumbersHelper

  def to_word(num)
    result = []
    digits = num.to_s.rjust(7, '0')
    result.push(process_numbers(digits[-3..-1], nil))
    result.push(process_numbers(digits[-6..-4], 1000))
    result.push(process_numbers(digits[-7], 1000000))
    result = result.reverse.join(" ")
    return result.split(' ')[1..-1].join(" ") if result.split(' ')[0] == "and"
    result
  end

  def process_numbers(digits, order)
    num_array = { 1 => "one", 2 => "two", 3 => "three", 4 => "four", 5 => "five", 6 => "six", 7 => "seven", 8 => "eight", 9 => "nine", 10 => "ten",
      11 => "eleven", 12 => "tweve", 13 => "thirteen", 14 => "fourteen", 15 => "fifteen", 16 => "sixteen", 17 => "seventeen", 18 => "eighteen",
      19 => "nineteen", 20 => "twenty", 30 => "thirty", 40 => "forty", 50 => "fifty", 60 => "sixty", 70 => "seventy", 80 => "eighty",
      90 => "ninety", 100 => "hundred", 1000 => "thousand", 1000000 => "million"
    }
    num = digits.to_i
    array = []
    if num <= 99 && num_array[num]
      array.push("and") unless order || digits[0] != "0" || digits == "000"
      array.push(num_array[num], num_array[order])
    elsif num <= 99
      array.push("and") unless order || digits[0] != "0" || digits == "000"
      array.push(num_array[num.to_s[0].to_i*10], num_array[num.to_s[-1].to_i])
      array.push(num_array[order]) if num != 0
    else
      array.push(num_array[num.to_s[0].to_i], num_array[size(num)])
      array.push("and") unless num_array[num] || num.to_s[-2..-1] == "00"
      array.push(process_numbers(num % 100, nil))
      array.push(num_array[order]) if order
    end
    array.join(" ")
  end

  def size(num)
    10**(num.digits.count - 1)
  end

  def next_page_links
    if @page + 3 >= @last_page
      max = @last_page -1
    else
      max = @page + 2
    end
    (@page + 1..max).to_a
  end

  def previous_page_links
    if @page - 2 < 2
      min = 1
    else
      min = @page - 2
    end
    (min..@page - 1).to_a
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Numbers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/numbers/_pagination.html.erb
<div class="pagination">
  <%= link_to 'Previous', numbers_path(page: @page - 1, quantity: @quantity), class: "btn btn-primary" unless @page == 0 %>
  <%= link_to "1", numbers_path(page: 0, quantity: @quantity), class: "btn btn-primary" unless @page == 0 %>

  <% previous_page_links.each do |link| %>
    <%= link_to link + 1, numbers_path(page: link, quantity: @quantity), class: "btn btn-primary" %>
  <% end %>

  <span class="current-page"> <%= @page + 1 %> </span>

  <% next_page_links.each do |link| %>
    <%= link_to link + 1, numbers_path(page: link, quantity: @quantity), class: "btn btn-primary" %>
  <% end %>

  <%= link_to @last_page + 1, numbers_path(page: @last_page, quantity: @quantity), class: "btn btn-primary" unless @page >= @last_page %>
  <%= link_to "Next", numbers_path(page: @page + 1, quantity: @quantity), class: "btn btn-primary" unless @page == @last_page %>
</div>

app/views/numbers/index.html.erb
<div class="container">
  <div class="search">
    <%= form_tag numbers_path, class: "numbers-form" do %>
      <div class="form-control">
        <label>Result per page
          <%= number_field_tag 'quantity', @quantity, within: 1...10000 %>
        </label>
        <%= submit_tag 'Save', class: "btn" %>
      </div>
      <%= render 'pagination' %>
    <% end %>
  </div>
  <ul class="list">
    <% @numbers.each do |num| %>
      <li class="number-output"><%= to_word(num) %></li>
      <div class="spacer"></div>
    <% end %>
  </ul>
</div>